CREATE TABLE IF NOT EXISTS video_news (
  id SERIAL PRIMARY KEY,
  video TEXT,
  text_latin TEXT,
  text_cyrillic TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  archived BOOLEAN NOT NULL DEFAULT FALSE,
  completed BOOLEAN NOT NULL DEFAULT FALSE
);