BEGIN;
ALTER TABLE news_posts ADD COLUMN created_at TIMESTAMP DEFAULT NOW();
ALTER TABLE news_posts ADD COLUMN edited_at TIMESTAMP DEFAULT NOW();
ALTER TABLE articles ADD COLUMN archived BOOLEAN DEFAULT FALSE;
ALTER TABLE articles ADD COLUMN created_at TIMESTAMP DEFAULT NOW();
ALTER TABLE articles ADD COLUMN edited_at TIMESTAMP DEFAULT NOW();
COMMIT;
